### ISSUE TITLE
Add meta-cards

### ISSUE THREAD

**Issue by koaning** [pola-rs/polars-web#29]
If you want the blogposts to do well on social media, it would help to have meta cards attached. The easiest way to check is by visiting https://metatags.io/. You can compare how https://calmcode.io would render vs. a blogpost and you should see a difference.

**Comment by ritchie46** [comment]
Thanks, should be fairly simple. Some meta tags and an image link if I recall correctly.

**Comment by carnarez** [comment]
For now I added some general meta-cards, for the whole website. If we want to do this for each endpoint/post independently I can modify the simple rendering script, and we can adapt something extracted from the front matter.

More work for the contributors though, which we are trying to avoid. What are your respective takes on this?

**Comment by ritchie46** [comment]
> For now I added some general meta-cards, for the whole website. If we want to do this for each endpoint/post independently I can modify the simple rendering script, and we can adapt something extracted from the front matter.
> 
> More work for the contributors though, which we are trying to avoid. What are your respective takes on this?

We could make it optional. If none provided we take the default.

**Comment by carnarez** [comment]
I used the front matter values for meta tags for each post. Making the `title` and `tldr` tags mandatory. If wishing to do so a custom image can also be provided for the meta tags (see #31).
