### ISSUE TITLE
Landing page for posts

### ISSUE THREAD

**Issue by koaning** [pola-rs/polars-web#31]
**Disclaimer** a lot of what I'm writing here is opinion, not fact. The goal is to start a discussion, not to suggest that I know better.

That said, I wonder if the landing page for all the posts could be slightly improved. Right now we're using Github handles as names, for SEO purposes it may be better to use the actual name. There's also a date missing for each post and there's something to be said to also list an image.

I'm listing the polars posts landing below and my blog for easy comparison. 

https://www.pola.rs/posts/

https://koaning.io/

**Comment by carnarez** [comment]
As you are the first guest I think your opinion acts as feedback; and we thank you for it. 😉 

Most of the pages can be more than slightly improved. This is a first take, destined to be modified. I got requested to keep the whole "framework" as simple as possible for maintainability purposes. Hence the blunt `Python`/`Jinja2`/vanilla-HTML combo.

Anyhow, all that to say that:
- [x] a date as been added to the post list, together with a possible [thumbnail](https://www.pola.rs/posts/guide/#extra-keys) (see below);
- [ ] the SEO comment has been heard and duly noted, and will be part of a future PR.

**To avoid reading the details:** to associate an image to a post in the list of posts, simply push it in the folder of said post, and put the filename as value of the `thumbnail` key in the front matter. If the image is out there instead, simply provide its URL. Beware, the height will be limited to 160px on the website.

```text
---
[...]
thumbnail: image.png
```

or
 
```text
---
[...]
thumbnail: https://domain.com/image.png
```
